AllCops:
  Exclude:
    - './vendor/**/*'

Style/FileName:
  Exclude:
    - '**/Dangerfile'
    - '**/Brewfile'
    - '**/Gemfile'
    - '**/Podfile'
    - '**/Rakefile'
    - '**/Fastfile'
    - '**/Deliverfile'
    - '**/Snapfile'
    - '**/*.gemspec'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 370