# AllCops:
#   TargetRubyVersion: 2.0
#   Exclude:
#     - './vendor/**/*'

AllCops:
  Exclude:
    - '**/Dangerfile'
    - '**/Brewfile'
    - '**/Gemfile'
    - '**/Podfile'
    - '**/Rakefile'
    - '**/Fastfile'
    - '**/Deliverfile'
    - '**/*.gemspec'
    - './vendor/**/*'

Metrics/BlockLength:
  Enabled: false