min_fastlane_version('2.70.3')

lane :release do
  verify_env_variables
  ensure_git_status_clean
  ensure_git_branch(branch: 'master')
  git_pull

  file = File.read('.././version.json')
  version_json = JSON.parse(file)
  version = version_json['version']

  changelog = read_changelog
  stamp_changelog(section_identifier: "Version #{version}")

  # Then push to git remote
  #
  git_commit(path: '.', message: 'Version Bump')
  push_to_git_remote

  # Preparing GitHub Release
  #
  github_release = get_github_release(url: 'RishabhTayal/itc-api', version: version)
  if (github_release || {}).fetch('body', '').empty?

    description = changelog

    github_release = set_github_release(
      repository_name: 'RishabhTayal/itc-api',
      name: version,
      tag_name: version,
      description: description,
      is_draft: false
    )

    release_url = github_release['html_url']
    puts 'Released: ' + release_url

    # message = [description, release_url].join("\n\n")
  end
end

desc 'Ensure all the requirement environment variables are provided'
desc 'this way the deployment script will fail early (and often)'
private_lane :verify_env_variables do
  ['GITHUB_API_TOKEN'].each do |variable|
    next unless ENV[variable].to_s.empty?
    UI.user_error!("Missing ENV variables #{variable}, make sure to provide one for fastlane to be successful")
  end
end
